# ################################################################################
# will check config.yml every half a minute.

# ################################################################################
# if enable, will connect to the wifi ssid on start. use this cmd to get the ssid:
# netsh wlan show profiles interface="wi-fi"
#
# required admin rights.
# not supported in linux.

adapter:
  enable: false
  reset_on_exit: false

  interface: "wi-fi"
  ssid: "default"

# ################################################################################
# cache server

cache:
  enable: true
  max_size: 1000
  ttl: 600

# ################################################################################
# dynamic dns

ddns:
  enable: false
  interval: 60
  provider: "dynu"

  api_key: ""
  domain_id: 0
  domain_name: ""

# ################################################################################
# in windows, not possible to set hostname to 0.0.0.0.
# in linux, either authbind or docker should work.

forward:
  custom:
    - "1.0.0.127.in-addr.arpa:localhost."
    - "localhost.in-addr.arpa:localhost."
    - "localhost:127.0.0.1"
  protocol: "dns"
  dns:
    - "" # example.com:127.0.0.1

upstream:
  message: "dns-message" # or "dns-json"
  protocol: "doh"
  doh:
    - "https://1.1.1.1/dns-query"
    - "https://1.0.0.1/dns-query"
    - "https://8.8.8.8/dns-query"
    - "https://8.8.4.4/dns-query"
    - "https://9.9.9.9/dns-query"

dns:
  hostname: "127.0.0.1"
  port: 53

doh:
  hostname: "127.0.0.1"
  port: 5053

dot:
  hostname: "127.0.0.1"
  port: 853

# ################################################################################
# logging

logging:
  level: "info"
  retention: 7

# ################################################################################
# use self-sign cert. one option, use mkcert.
# or update the certs in the certs folder.
#
# use by doh, dot, web frontend. default self-signed certs.

ssl:
  certfile: "certs/cert.pem"
  keyfile: "certs/key.pem"

# ################################################################################
# experimental wip web frontend.

web:
  enable: true
  hostname: "127.0.0.1"
  port: 5050

# ################################################################################
# adsblock

adsblock:
  reload: false # true to force reload on first run
  custom:
    - "" # example.com

  whitelist:
    - "" # example.com

  blacklist: # get it from https://firebog.net/
    # suspicious lists
    - "https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt"
    - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts"
    - "https://v.firebog.net/hosts/static/w3kbl.txt"
    - "https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt"
    - "https://someonewhocares.org/hosts/zero/hosts"
    - "https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts"
    - "https://winhelp2002.mvps.org/hosts.txt"
    - "https://v.firebog.net/hosts/neohostsbasic.txt"
    - "https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt"
    - "https://paulgb.github.io/BarbBlock/blacklists/hosts-file.txt"

    # advertising lists
    - "https://adaway.org/hosts.txt"
    - "https://v.firebog.net/hosts/AdguardDNS.txt"
    - "https://v.firebog.net/hosts/Admiral.txt"
    - "https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt"
    - "https://v.firebog.net/hosts/Easylist.txt"
    - "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext"
    - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts"
    - "https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts"

    # tracking & telemetry lists
    - "https://v.firebog.net/hosts/Easyprivacy.txt"
    - "https://v.firebog.net/hosts/Prigent-Ads.txt"
    - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts"
    - "https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt"
    - "https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt"
    - "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt"
    - "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt"
    - "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt"
    - "https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt"

    # malicious lists
    - "https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt"
    - "https://v.firebog.net/hosts/Prigent-Crypto.txt"
    - "https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts"
    - "https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt"
    - "https://phishing.army/download/phishing_army_blocklist_extended.txt"
    - "https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt"
    - "https://v.firebog.net/hosts/RPiList-Malware.txt"
    - "https://v.firebog.net/hosts/RPiList-Phishing.txt"
    - "https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt"
    - "https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts"
    - "https://urlhaus.abuse.ch/downloads/hostfile/"
    - "https://lists.cyberhost.uk/malware.txt"
    - "https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt"
    - "https://v.firebog.net/hosts/Prigent-Malware.txt"
    - "https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/wildcard_domains/scams.txt"

    # other lists
    - "https://raw.githubusercontent.com/chadmayfield/my-pihole-blocklists/master/lists/pi_blocklist_porn_top1m.list"
    - "https://v.firebog.net/hosts/Prigent-Adult.txt"
    - "https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt"
